baseurl: "/home"
nav:
  - title: "Português (BR)"
    url: "/pt-br/"
  - title: "Deutsch (DE)"
    url: "/de-de/"
  - title: "English (US)"
    url: "/en-us/"


social:
  linkedin: "https://www.linkedin.com/in/pedro-arantes-a88099140/"
