
# Theme settings
theme: minima                       # Using the default GitHub Pages theme 'minima'
skin: dark                        # Customize the theme's appearance (options: 'default', 'dark', etc.)

# Author information
author:
  name: "Pedro Arantes"             # Your name as you want it displayed
  email: "p.arantes@protonmail.com"   # Your contact email

# Other customization options
# You can define custom variables to use in your layouts, for example:
social:
  linkedin: https://www.linkedin.com/in/pedro-arantes-a88099140/
